import { IPost } from "./model/post";
export const testData: IPost[] = [
    {
        _id:  "1",
        date: "20170723",
        value: "mahathir's cronies vs najib's cronies",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
            "mahathir",
        ],
        semantic_value: "unassigned",
        belongs_to: "p0",
    },
    {
        _id:  "2",
        date: "20170723",
        value: "  jho low, the 'unofficial' consultant of 1mdb, a friend of najib's stepson",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "1mdb",
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p1",
    },
    {
        _id:  "3",
        date: "20170723",
        value: "  salam dato rocky",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "4",
        date: "20170723",
        value: "\"then please give me the name of one malaysian individual who deserves or qualifies to be called a crony of najib razak",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "5",
        date: "20170723",
        value: "\"answer: razak baginda, deepak carpet and jho low",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "6",
        date: "20170723",
        value: " to name the prominent few",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "7",
        date: "20170723",
        value: "at least, with dr",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "8",
        date: "20170723",
        value: "m's cronies such as ytl, ananda krishnan, syed mohktar bukhary",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "9",
        date: "20170723",
        value: " hundreds of thousand rakyat could earn a living and raise families, working for them",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "10",
        date: "20170723",
        value: " the gomen too could collect taxes in form of employees remuneration, corporate taxes and the wealth of dr",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "11",
        date: "20170723",
        value: "m's cronies",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "12",
        date: "20170723",
        value: " eternally, as long as their companies is doing well",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "13",
        date: "20170723",
        value: "however, with najib's cronies (razak baginda, deepak carpet and jho low)",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "14",
        date: "20170723",
        value: " what does the rakyat and gomen, get in return",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "15",
        date: "20170723",
        value: " lick their dick",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
        ],
        semantic_value: "unassigned",
        belongs_to: "p2",
    },
    {
        _id:  "16",
        date: "20170723",
        value: "  the dedak has really damage you brain en rocky (pun intended for your datukship is illegitimate)",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
            "rosmah",
        ],
        semantic_value: "unassigned",
        belongs_to: "p3",
    },
    {
        _id:  "17",
        date: "20170723",
        value: " najib only enrich himself, rosmah, his family and his advisor such as jho lo, farid ridzuan, habibur rahman and few other major dedakians",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
            "rosmah",
        ],
        semantic_value: "unassigned",
        belongs_to: "p3",
    },
    {
        _id:  "18",
        date: "20170723",
        value: "cant believe you didnt know that but dedak will do that to people",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "najib",
            "rosmah",
        ],
        semantic_value: "unassigned",
        belongs_to: "p3",
    },
    {
        _id:  "19",
        date: "20170723",
        value: "  salam rd,the last line is not you, if i may just say",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "1mdb",
            "najib",
            "mahathir",
        ],
        semantic_value: "unassigned",
        belongs_to: "p4",
    },
    {
        _id:  "20",
        date: "20170723",
        value: " :-=)i knew jho lo's name would come u, though",
        origin: "scrape-results/blog/rockybru_20170801_160034.csv",
        source: "blog",
        related_to: [
            "1mdb",
            "najib",
            "mahathir",
        ],
        semantic_value: "unassigned",
        belongs_to: "p4",
    },
];
